# Sample workflow for building and deploying a Jekyll site to GitHub Pages
name: Deploy Jekyll with GitHub Pages dependencies preinstalled

on:
  push:
    branches: ["master"]  # Trigger on pushes to the master branch
  workflow_dispatch:  # Allow manual triggering from the Actions tab

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false  # Don't cancel in-progress deployments

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner
    steps:
      - name: Checkout
        uses: actions/checkout@v4  # Check out the repository code

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'  # Set Node.js to version 20

      - name: Setup Pages
        uses: actions/configure-pages@v5  # Configure GitHub Pages

      - name: Install dependencies
        run: npm install  # Install dependencies specified in package.json

      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./_site  # Build the site and output to the _site directory

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          name: "github-pages-${{ github.run_id }}"  # Name the artifact uniquely

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: "github-pages-${{ github.run_id }}"  # Download the built site artifact

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4  # Deploy the site to GitHub Pages
